variables:
- name: major
  value: '2'
- name: minor
  value: '0'
- name: extensionName
  value: 'team-calendar'
- name: marketplaceServiceConnection
  value: 'marketplaceServiceConnection'
- name: publisherId
  value: 'ms-devlabs'
- name: publicExtensionName
  value: "Team Calendar"

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure-pipelines-steps.yml
  
